### ISSUE TITLE
Регистр букв в includes/moosenews.php

### ISSUE THREAD

**Issue by linuxdv** [brevis/moosenews#1]
При переносе на линукс сервер плагин не заработал.

Пришлось править строку includes/moosenews.php на includes/MooseNews.php

Когда wordpress работал на  сервере с макосью такой баг не появлялся, так как макось не учитывает регистр букв.

**Comment by brevis** [comment]
Прямо таки афигеть! 
Я был убежден, что макось тоже "чувствительна к регистру".
Спасибо!

**Comment by linuxdv** [comment]
я нищеброд и макоси у меня нет, но слышал такую байку что якобы чувствительность к регистру в макоси можно  включить только принудительно. Так что неудивительно что в обычной жизни такого не встретишь.
